# This file stores configurations for your Shopify app.

scopes = "write_products,read_orders,read_customers,read_products,read_inventory,write_customer_payment_methods,write_own_subscription_contracts,read_own_subscription_contracts"
